title: "Tristan Tomilin"
description: "My research and projects"
baseurl: "" # Leave this empty for GitHub Pages
url: "https://ttomilin.github.io"
theme: jekyll-theme-minimal
author:
  name: "Tristan Tomilin"
  email: "t.tomilin@tue.nl"
  github: "https://github.com/TTomilin"
